Catch uncaught opener errors
webpack-contrib/webpack-bundle-analyzer pull request #382
Opened 2020-09-22 04:31 UTC by wbobeirne

Closes #381.

2020-09-24 06:39 UTC, valscion commented
Please sign CLA and fix CI ☺️

2020-09-28 13:55 UTC, th0r requested changes

2020-09-28 13:55 UTC, th0r commented on src/viewer.js
> +    logger.debug(`Opener failed to open "${uri}":\n${err}`)
`logger` is not defined.

2020-09-28 13:55 UTC, th0r commented on src/viewer.js
> +function safeOpener(uri) {
Let's better move this function to `utils.js`.

2020-09-28 15:58 UTC, th0r requested changes

2020-09-28 15:58 UTC, th0r commented on package-lock.json
> +  "version": "3.9.0",
Don't change the version in this PR please.

2020-09-28 15:58 UTC, th0r commented on src/utils.js
> +exports.safeOpener = function (uri, logger) {
Let's better rename it to just `open` please.

2020-09-28 17:31 UTC, th0r approved these changes

2020-09-28 17:32 UTC, merged

2020-09-28 17:32 UTC, th0r commented
Thanks!