Replace mkdirp with builtin recursive flag
webpack-contrib/webpack-bundle-analyzer pull request #391
Opened 2020-11-06 16:48 UTC by TrySound

In node 10.12 mkdir got new recursive flag which provides the same
functionality as mkdirp.

See here https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback

Also node 10 got builtin promisified `fs` utilities.

See here https://nodejs.org/api/fs.html#fs_fs_promises_api

2020-11-06 17:07 UTC, th0r requested changes

2020-11-06 17:07 UTC, th0r commented on src/BundleAnalyzerPlugin.js
> +const fs = reqiore('fs');
```suggestion
const fs = require('fs');
```

2020-11-06 17:07 UTC, th0r commented on src/viewer.js
> +  await fs.promises.writeFileSync(reportFilename, JSON.stringify(chartData));
```suggestion
  await fs.promises.writeFile(reportFilename, JSON.stringify(chartData));
```

2020-11-06 20:07 UTC, th0r requested changes

2020-11-06 20:07 UTC, th0r commented on package.json
> -    "mkdirp": "^1.0.4",
Removing this line is not enough - `package-lock.json` should also be updated. Run `npm rm mkdirp` to properly remove dependency please.

2020-11-06 21:23 UTC, th0r approved these changes

2020-11-07 07:56 UTC, th0r commented
`licence/cla` check is stuck for some reason. @valscion do you know how to fix it?

2020-11-08 19:31 UTC, merged

2020-11-08 19:31 UTC, th0r commented
Thanks!

2020-11-09 08:06 UTC, valscion commented
> `licence/cla` check is stuck for some reason. @valscion do you know how to fix it?

Closing and reopening the pull request triggers a new `licence/cla` check in case the service was down for some reason in the past — that's how I've dealt with these situations before 😅

2020-11-09 10:08 UTC, TrySound commented
I just do empty commits in such cases

2020-11-30 14:02 UTC, valscion commented
Released in v4.2.0 :relaxed:. Thank you for your contributions!