Setup GitHub actions to run tests and lint
webpack-contrib/webpack-bundle-analyzer pull request #402
Opened 2020-12-02 07:31 UTC by valscion

Resolves https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/400

2020-12-02 07:46 UTC, valscion commented
I disabled the `continuous-integration/travis-ci` branch protection for now so that this PR is not blocked on advancing. If @th0r you feel like this is good to go, I can add branch protections for the GitHub actions if necessary.

2020-12-02 11:19 UTC, th0r commented
I wonder is it possible to add `Node.js` prefix to version numbers as now it's a bit not obvious what do these numbers mean?

![image](https://user-images.githubusercontent.com/302213/100866200-5e3b6400-34a9-11eb-876d-1cc998f0eeb0.png)

2020-12-02 11:29 UTC, valscion commented
I don't know — I can check if that's possible when I have the time ☺️

2020-12-03 09:08 UTC, valscion commented
It now looks like so:

<img width="863" alt="Replace_Travis_with_GitHub_actions_as_CI_by_valscion_·_Pull_Request__402_·_webpack-contrib_webpack-bundle-analyzer" src="https://user-images.githubusercontent.com/482561/100987910-c6488380-3557-11eb-83d4-948a26d917ef.png">

It seems quite simple to change the name to whatever we want as can be seen by fdb5a0e08b102ca1e1519d2995a35a3b84c4758b — feel free to make a direct code suggestion to this PR if you have a better wording in mind ☺️

2020-12-03 11:32 UTC, th0r requested changes

2020-12-03 11:32 UTC, th0r commented on .github/workflows/main.yml
> +    name: Tests on node ${{ matrix.node }}
Just a small suggestion:
```suggestion
    name: Tests on Node.js v${{ matrix.node }}
```

2020-12-03 13:04 UTC, th0r approved these changes
Great, thanks!

2020-12-03 13:05 UTC, merged

2020-12-03 13:06 UTC, valscion commented
> I can add branch protections for the GitHub actions if necessary.

Do we need the branch protections? I'm not sure if they're necessary — a red CI should be enough for us to avoid merging pull requests.

The CLA-check of course stays as a required status check.

2020-12-03 13:28 UTC, th0r commented
> Do we need the branch protections?

I don't even know what is that =)

2020-12-03 14:03 UTC, valscion commented
Ah, it's this one:

<img width="933" alt="feat__Render_Selected_Module_Size_Total_by_vwb_·_Pull_Request__346_·_webpack-contrib_webpack-bundle-analyzer" src="https://user-images.githubusercontent.com/482561/101027559-d163d980-3580-11eb-8123-3d5d5065af46.png">

So one can't merge a pull request (unless they're an admin and admin overrule is allowed) if a required status check is not successful.

We could configure some or all of the GitHub Actions status checks to be required to be successful to allow merging via https://github.com/webpack-contrib/webpack-bundle-analyzer/settings/branches, from here:

<img width="1373" alt="Branch_protection_rule" src="https://user-images.githubusercontent.com/482561/101027741-1982fc00-3581-11eb-8bd4-289f929a0fc2.png">

2020-12-03 16:12 UTC, th0r commented
Ah, ok, thanks for the explanation. I don't think we need it.

2020-12-03 18:57 UTC, valscion commented
Yeah I think the same, let's keep it as it is now :+1: